server:
  port:
    8080

spring:
  # MySQL 접속 정보 설정
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # OpenFeign Content Type 설정
  cloud:
    openfeign:
      client:
        DEBUG
      oauth2:
        enabled: true
      encoder:
        charset-from-content-type: true