server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/birthday
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver



    # url: jdbc:mysql://?????? ??/birthday?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    # username: ?????? ???
    # password : ?????? ????
